### ISSUE TITLE
Property/Component Viewer

### ISSUE THREAD

**Issue by xdevapps** [xdevapps/ApexGameEngine#10]
Show the properties and components of the selected object

**Comment by xdevapps** [comment]
Base implementation is ready.

TODO: Implement built-in components as listed in #

**Comment by xdevapps** [comment]
TODO: Implement macros to automatically display user-defined components with reflection

**Comment by athanggupte** [comment]
Closing this issue. Progress on user-defined component UI will be tracked in #17
